name: Build Windows x64
permissions: 
  contents: write
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rsync-wrapper-windows-x64
        path: target/x86_64-pc-windows-msvc/release/*.exe
    
    - name: Create release assets
      if: github.event_name == 'release'
      run: |
        mkdir release
        copy target\x86_64-pc-windows-msvc\release\*.exe release\
        
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
